"""empty message

Revision ID: 694120e1e3c3
Revises: 
Create Date: 2024-06-30 16:06:20.477082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '694120e1e3c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interest_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('statement_due_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('minimum_payment_due_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('billing_cycle_days', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card', schema=None) as batch_op:
        batch_op.drop_column('billing_cycle_days')
        batch_op.drop_column('minimum_payment_due_date')
        batch_op.drop_column('statement_due_date')
        batch_op.drop_column('interest_rate')

    # ### end Alembic commands ###
