"""Add currency fields to main models

Revision ID: dc9a5516e68f
Revises: 694120e1e3c3
Create Date: 2025-07-10 22:11:26.173733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc9a5516e68f'
down_revision = '694120e1e3c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=8), nullable=False, server_default='USD'))

    with op.batch_alter_table('budget_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=8), nullable=False, server_default='USD'))

    with op.batch_alter_table('credit_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=8), nullable=False, server_default='USD'))

    with op.batch_alter_table('debt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=8), nullable=False, server_default='USD'))

    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=8), nullable=False, server_default='USD'))

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=8), nullable=False, server_default='USD'))

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=8), nullable=False, server_default='USD'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('currency')

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_column('currency')

    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.drop_column('currency')

    with op.batch_alter_table('debt', schema=None) as batch_op:
        batch_op.drop_column('currency')

    with op.batch_alter_table('credit_card', schema=None) as batch_op:
        batch_op.drop_column('currency')

    with op.batch_alter_table('budget_category', schema=None) as batch_op:
        batch_op.drop_column('currency')

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
